services:
  vaultwarden2keepass:
    container_name: vaultwarden2keepass
    build: https://github.com/genericFJS/vaultwarden2keepass.git
    command: npm run start
    volumes:
      - "./backup:/app/backup"
      # Cache bitwarden cli config (else every start of the script would trigger a "new device" mail)
      - "./backup/cli-config:/root/.config/Bitwarden CLI/"
    environment:
      # Mandatory
      - "URL=https://vault.bitwarden.com/"
      - "BW_CLIENTID=user.aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      - "BW_CLIENTSECRET=abcdefghijklmnopqrstuvwxz01234"
      - "BW_PASSWORD=Y29ycmVjdGhvcnNlYmF0dGVyeXN0YXBsZQ=="

      # Optional
      - "KEEPASS_BACKUP_PASSWORD=VHIwdWI0ZG9yJjM="
      - "KEEPASS_BACKUP_KEYFILE_PATH=/path/to/keyfile.keyx"
      - "ATTACHMENT_TEMP_FOLDER=/tmp"
      - "MAX_ATTACHMENT_BYTES=100000"
      - "KEEPASS_BACKUP_PATH=./backup"
      - "KEEPASS_BACKUP_FILE_NAME=BitwardenBackup"
      - "KEEPASS_BACKUP_DATABASE_NAME=BitwardenBackup_%date%"
      - "ORGANIZATIONS_GROUP_NAME=Organizations"
      - "ORGANIZATION_MODE=flat"
      - "ORGANIZATION_FOLDERS_NAME=Folders"
      - "ORGANIZATION_COLLECTIONS_NAME=Collections"
